### PR TITLE
[Types] Add .d.ts files and replace Collection with djs pkg

### PR DESCRIPTION
**Pull request by PapiOphidian**
The title of this PR is self explanatory.
The JSDoc annotations do not play nicely with TypeScript and there is no @types/taihou package, so I thought I'd make a PR to remedy this issue.

This PR also removes the src/Collection mod in favor of using the @discordjs/Collection package from NPM which is in all practicality, the same thing as what was exported previously, but more up to date.

Some info retrieved from JSDoc annotations such as comments will no longer be accessible by the user in editor unless they read the source. If comments for the user are a priority, I can add them in.

Another thing I did was I fixed some incorrect references or spelling to types. I did not try to fix all of the errors that my editor told me were present when creating the .d.ts files.

All .d.ts files were made by hand as I was reading the JSDoc annotations and reading the index signatures for the modules.

### CODE REVIEW

**Comment by Niputi** [comment]
you can simplify this pr with only a tsconfig which outputs definition file by reading the Javascript files.

would be nice if you did spelling mistakes in seperate pr as it looks better in commits

**Comment by PapiOphidian** [comment]
The JSDoc annotations aren't totally typesafe or complete which is why I opted to manually write them.

TS gives a bit more fine grain control such as overloads I included in Base

**Comment by PwaPois** [comment]
Hey there, yes, the JSDoc comments are supposed to be included in the IntelliSense.  

As for collections, this package is meant to be as dependency-less as possible and therefore isn't supposed to have any more dependency than Axios. The collections are also only for internal use, they do not need to be up to date, in fact, they even are fairly overkill for how few uses the package makes of them

That aside, the rest of the PR seems fine, I'll get around to testing it and will merge it when the issues above are out of the picture

**Comment by PapiOphidian** [comment]
This should be all that was requested unless I missed something. Once this is merged, I'll make a PR to fix the spelling mistakes and other typings cleanup such as index members being any and rename types like String => string since the capitalized names refer to the constructor type instead of the primitives

**Comment by PwaPois** [comment]
In that case, I'll wait until your follow-up PR to publish a new version, that alright with you?

**Comment by PapiOphidian** [comment]
yes

**Pull request merged**
